### ISSUE TITLE
mousewheel slide end

### ISSUE THREAD

**Issue by Hazantip** [OwlCarousel2/OwlCarousel2#1010]
Hi, look at my situation please. Can't find a solution;
I want to slide items in carousel by mousewheel and i using for this goal moushweel plugin, but i want to continue to scroll page when i reached last slide.

caseSlider.on('mousewheel', '.owl-wrapper', function (e) {

			var n = $(this).find('.owl-item').length;
			var c = $(this).find('.owl-item.active').index();
			if ( (c+1) === n ) {
				console.log('end');
			} else {
				if (e.deltaY>0) {
					$(this).closest(caseSlider).trigger('owl.next');
				} else {
					$(this).closest(caseSlider).trigger('owl.prev');
				}
			}

			e.preventDefault();
		});

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
