### ISSUE TITLE
Normal Scrolling for Mobile

### ISSUE THREAD

**Issue by jacobkossman** [OwlCarousel2/OwlCarousel2#1011]
Hey! Awesome plugin. I'm working on a carousel that shows multiple items at the same time and the drag on mobile has no inertia (like normal scrolling would) so I was wondering if it's possible to "deactivate" the single item at a time type scrolling and make it a normal horizontal scroll for easier navigation on mobile devices? Thanks!

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
