### ISSUE TITLE
OwlCarousel 2 Mouse wheel issue

### ISSUE THREAD

**Issue by sanjukanwasi** [OwlCarousel2/OwlCarousel2#1031]
having issue with mouse wheel functionality after applying loop:false... 

Basically I'm trying to get it to vertically scroll from one slide to the other and when it reached on last  slide, then i want to scroll my page to next section...

**Comment by sanjukanwasi** [comment]
it's skipping some slides during mousewheel......like following order:

1-3-4 ...
and some time 1-2-4.... 

mainly it not working one by one slide..

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
