### ISSUE TITLE
Destroy.owl.carousel and lot of error _checkVisibile

### ISSUE THREAD

**Issue by Amstramgram** [OwlCarousel2/OwlCarousel2#1070]
Hello,

i don't know if it's bug but i have this error:
```" Uncaught TypeError: Cannot read property '_checkVisibile' of null "``` for each second who past.

I load my gallery basically:
```
$(document).ready(function(){
		$('.basic-owl').owlCarousel({
			loop: false,
			dots: true,
			nav: true,
			items: 1
		});
	});
```
and when i click on ```<a></a>``` this:
```
var $owl = $('.basic-owl');
			$owl.trigger('destroy.owl.carousel');
			$owl.html($owl.find('.owl-stage-outer').html()).removeClass('owl-loaded');
			$owl.owlCarousel({
				loop: false,
				dots: true,
				nav: true,
				items: 1
			});
```

I do this because the div parent of gallery have display none style and plugin doesn't set correctly width for owl-stage.

How i can solved my error ?

Thank you.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
