### ISSUE TITLE
hide navText if images < items

### ISSUE THREAD

**Issue by ezersky** [OwlCarousel2/OwlCarousel2#1078]
Hi!

How to hide navText if quantity of images less than items

Screenshot of problem: http://i.imgur.com/cQ8uZkD.png

my code

```javascript
	$('.images').owlCarousel({
		/*autoplay: true,
		autoplayHoverPause: true,
    loop: true,*/
    margin: 5,
    responsiveClass: true,
    dots: false,
    nav:true,
    navText: ['<i class="fa fa-arrow-left"></i>','<i class="fa fa-arrow-right"></i>'],
    responsive:{
      0:{
        items:3
      },
      600:{
        items:3
      },
      1000:{
        items:4
      }
    }
	});
```

**Comment by eparisio** [comment]
Teorically via css if you don't have loop, the elements should have the class .disabled

**Comment by ezersky** [comment]
>>Teorically via css if you don't have loop, the elements should have the class .disabled

Does not work with your solution...

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
