### ISSUE TITLE
1: centering items 2: wrapping items when resizing broswer window

### ISSUE THREAD

**Issue by janaslani** [OwlCarousel2/OwlCarousel2#1089]
Hi there,

Is there a way to center the items in the second carousel?

Thanks,
Edwin.

<img width="1201" alt="screen shot 2015-10-16 at 12 42 39 pm" src="https://cloud.githubusercontent.com/assets/15163245/10551743/a4326506-7403-11e5-9d8e-0dd95a371a45.png">

<pre>
    stagePadding: 50,
    loop:true,
    margin:10,
    responsive:{
        0:{
            items:3
        },
        600:{
            items:5
        },
        1000:{
            items:7
        }
    }
</pre>

...and wrapping also occurs when re-sizing browser window:

<img width="1116" alt="screen shot 2015-10-16 at 3 17 47 pm" src="https://cloud.githubusercontent.com/assets/15163245/10554549/33e974d6-7419-11e5-877b-814125f26058.png">

**Comment by IgorCode** [comment]
How about setting [center](http://smashingboxes.github.io/OwlCarousel2/docs/api-options.html#center) to true?

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
