### ISSUE TITLE
Last slide jumps under the first slide

### ISSUE THREAD

**Issue by karaliunas** [OwlCarousel2/OwlCarousel2#1090]
Hi, this happens because there is not enough width for the last slide. If I remove its margin-right - it comes back to the right place.
You can see the demo here: http://karaliunaite.com/portraits/

Is there a way to fix it in JS? Thank you!

**Comment by rmiraftabi** [comment]
With the latest Beta adding the following inside the else after line 341 will solve the problem and remove the right margin from the last or left margin from the first element. The cause for this issue is simply an issue with rounding in browser - sometimes there is enough room and other times there isn't. 

				css = { 'width': this.settings.autoWidth ? 'auto' : width - this.settings.margin };
				if (this.settings.rtl) {
					css['margin-left'] = '0px';
					this.$stage.children().first().css(css);
				} else {
					css['margin-right'] = '0px';
					this.$stage.children().last().css(css);
				}

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
