### ISSUE TITLE
Remove items and then later add them back in

### ISSUE THREAD

**Issue by talbotini** [OwlCarousel2/OwlCarousel2#1093]
I have worked through the bug with the remove event (using 2.4) but I can't work out how to add back in later the items that were removed.

There is a user interaction on my page that filters the items that show up. I am triggering the remove event to take out items that do not meet the filter requirements. Problem is when the user changes their filter selection all of the removed items are now permanently gone.

I tried using the destroy event and then re-calling the carousel but that doesn't seem to do anything. The destroy seems successful, but cant get it to re-build itself with the original content. Anyone have an example of this?

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
