### ISSUE TITLE
Loop issuse in owl carousel

### ISSUE THREAD

**Issue by rohit502** [OwlCarousel2/OwlCarousel2#1095]
I need to show the caption div when current item  is focused.
i am able to show the caption but when second last image focused with cation last image also show caption in loop. 

In first loop all info div show when image is focused but after first loop last image already comes with caption.
for Refrence: http://jsfiddle.net/1qdurrLz/92/
 Here is the  jquery code:

$(document).ready(function () {
    $('#slider').on('initialized.owl.carousel change.owl.carousel changed.owl.carousel ', function (e) {
        if (!e.namespace || e.type != 'initialized' && e.property.name != 'position') return;
        var current = e.relatedTarget.current()
        var items = $(this).find('.owl-stage').children()
        //alert(current);
        var add = e.type == 'changed' || e.type == 'initialized'
       items.eq(e.relatedTarget.normalize(current)).toggleClass('current', add)
    }).owlCarousel({
        items: 3,
        margin: 10,
        itemsDesktop : [1199,3],
        itemsDesktopSmall: [979, 3],
        autoplay:true,
        autoplayTimeout:2000,
        autoplayHoverPause: true,
        //autoHeight: true,
        responsive: true,
        center: true,
        dots:false,
        nav: true,
        loop: true
    });
})

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
