### ISSUE TITLE
lazyLoad without Loop

### ISSUE THREAD

**Issue by gatsu83** [OwlCarousel2/OwlCarousel2#1096]
When i initialize the carousel with at least these options:
```
{
 items: 5, // any item number >1
 lazyLoad:true,
 loop:false
}
```

only the first image is loaded.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
