### ISSUE TITLE
navigation remains disabled when resizing and hitting a responsive step

### ISSUE THREAD

**Issue by gatsu83** [OwlCarousel2/OwlCarousel2#1097]
In a multi item carousel without loop, if i have less items, the navigation is disabled (as it should be). But if i resize the browser and my responsive step has set less items than the elements of my carousel, the navigation remains disabled.

Example:
HTML:
```
<div class="owl-carousel">
    <div class="item"><h4>1</h4></div>
    <div class="item"><h4>2</h4></div>
    <div class="item"><h4>3</h4></div>
    <div class="item"><h4>4</h4></div>
</div>
```
JS:
```
$('.owl-carousel').owlCarousel({
    items: 5,
    loop:false,
    nav:true,
    responsive: {
                0: {
                    items: 1
                },
                479: {
                    items: 1
                },
                768: {
                    items: 2
                },
                980: {
                    items: 3
                },
                1199: {
                    items: 4
                },
                1350: {
                    items: 5
                }
            },
});
```

**Comment by rafael-renan-pacheco** [comment]
Working fine here.

Check if the navigation controls are being hidden by some unexpected css, or by some html element when reaching the responsive width.

**Comment by daviddeutsch** [comment]
Yeah, this worked for me in other projects as well.

(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
