### ISSUE TITLE
Mobile Double Click Issue

### ISSUE THREAD

**Issue by Akimoto001** [OwlCarousel2/OwlCarousel2#1106]
Hello,
The problem occurs when I scroll through the carousel on mobile. When the page loads I can click on each image (which I've made a link) and it changes no problem. However, when I scroll back through the links, it then takes a double click to activate the change.

Perhaps this is too broad, but I was wondering if anyone else was experiencing this?

**Comment by joppuyo** [comment]
I can reproduce this issue. It looks like it's caused when trying to click an element near the position where you started the drag. I have narrowed down the culprit to [this line](https://github.com/smashingboxes/OwlCarousel2/blob/a13845c0d2275ce6d3174454bf50f5bb19f5af03/src/js/owl.carousel.js#L813).

If you comment it out, the click event starts working normally and you don't need to double click to activate elements.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
