### ISSUE TITLE
fadeOut/In animations not working in Firefox

### ISSUE THREAD

**Issue by Twansparant** [OwlCarousel2/OwlCarousel2#1108]
Hi there,

I love your carousel plugin, but I can't seem to get the fade animations to work in Firefox (version 41.0.2 on a Mac). I have tested and stripped everything down to a codepen: http://codepen.io/Twansparant/full/JYvzej/

Where the slides should fadeIn & Out, it just flickers to the new slide. In all the other browsers (tested in Chrome v46, Safari v9, Opera v32, Internet Explorer 10) it does work like expected, even in Firefox Developer Edition (v43) it works correctly.

Is this a known bug or am I missing something here?
Thanks!

**Comment by Twansparant** [comment]
Typical, after days of debugging I just found the problem.
It's this line in **owl.carousel.min.css**:
```css
.owl-carousel .owl-item img {
    transform-style: preserve-3d;
}
```
That's causing this behaviour in Firefox.
When I set it to `flat` or `inherit`, the animations suddenly work but sometimes there is still a little flicker between 2 slides, but still only in Firefox.

**Comment by TMWagner** [comment]
So... where are the transition options documented? I'm finding absolutely nothing on for the beta 2.x release branch

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
