### ISSUE TITLE
Error animation when data-hash set on div

### ISSUE THREAD

**Issue by davydkoff** [OwlCarousel2/OwlCarousel2#1111]
Hello!
When i add data-hash into div
< div class="item" data-hash="one" >
animation from first dot to last dot not working.
Without "data-hash" works fine, but when click on first dot, then last - animation scroll to left. It should be?

if there is data-hash - scroll only to right (if click penultimate point after first etc).
Thanks

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
