### ISSUE TITLE
Clicking slider while in transition causes slider to go back

### ISSUE THREAD

**Issue by iblack10** [OwlCarousel2/OwlCarousel2#1112]
If you click a slide while it's in the process of transitioning it won't follow the link on the slide. Instead, it will reverse the animation and take you back to the slide you were on meaning you have to click again to follow the link.

This could be intended behaviour?

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
