### ISSUE TITLE
Problem magnific popup lightbox with loop true image cloned

### ISSUE THREAD

**Issue by nicolas92** [OwlCarousel2/OwlCarousel2#1113]
Hello, first of all, thank you for creating owl carousel, it's great, I will use it for all my themes :)
There is a small problem with magnific popup when I put loop true in owl carousel.
For the gallery post format, when I click on the pictures, they are shown in lightbox, the cloned image is not displayed in the lightbox but in new page.
Can you help me?
Thank you a lot.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.

**Comment by mathetos** [comment]
I'm actually using this version of Owl Carousel in a WordPress plugin and it has an option to open the image in a lightbox (called FooBox) and we're experiencing the same problem, but not reliably.
https://wordpress.org/plugins/foogallery-owl-carousel-template/

Here's examples and issues:
1) [On this site](http://www.emilycolin.com/in-the-works/), you'll see that when navigate through the loop to the first image again the image does NOT show up in the lightbox. That behavior is consistent across all browsers.

2) [But on my personal site](https://www.mattcromwell.com/products/foogallery-owl-carousel/) the issue only happens in FireFox.

3) Lastly, I can't get the issue to happen at all locally in any browser.

I know that adding the WordPress environment and this implementation introduces new potential conflicts, but you can see in the markup and the initialization script that these are just standard Owl Carousel instances.

Would love some feedback or insight on how this might be happening.

Thanks!
