### ISSUE TITLE
LazyLoad When items=3 and images=2

### ISSUE THREAD

**Issue by galatent** [OwlCarousel2/OwlCarousel2#1121]
I have encountered an issue with owl carousel 2.0 beta 4.
With lazyload enabled and specifically only when items is set to 3 and with 2 images, it will only make the first image visible. 
If I reduce the items to 2 it works OK, if I increase the number of images above 2 it works OK.

Settings:
autoplay: true,
autoplayTimeout : 3000,
autoplaySpeed : 1000,
items : 3,
lazyLoad : true,
loop : true,
dots : true,

With the above settings:

and 1 image:
![image](https://cloud.githubusercontent.com/assets/11752798/11089526/52a0b044-8862-11e5-87eb-5739e8ac9e81.png)

and 2 images:
![image](https://cloud.githubusercontent.com/assets/11752798/11089497/1139bf88-8862-11e5-9417-69d707345595.png)

and 3 images:
![image](https://cloud.githubusercontent.com/assets/11752798/11089508/331796ac-8862-11e5-99af-0c1352b7847f.png)

**Comment by galatent** [comment]
I've found a workaround for this, from rolling back some of the code to beta3.

Find this line:
clones && $.each(this._core.clones(this._core.relative(position++)), load);

Replace with these 2 lines:
clones && $.each(this._core.clones(this._core.relative(position)), load);
position++;


Find the function "Owl.prototype.normalize" and replace with this code from beta3:

Owl.prototype.normalize = function(position, relative) {
		var n = this._items.length,
			m = relative ? 0 : this._clones.length;

		if (!$.isNumeric(position) || n < 1) {
			position = undefined;
		} else if (position < 0 || position >= n + m) {
			position = ((position - m / 2) % n + n) % n + m / 2;
		}

		return position;
	};

**Comment by flyrootmedia** [comment]
Just wanted to +1 this issue. I have been experiencing the same problem with the beta 2.4 release. It doesn't seem specific to the number of images, but rather when set to lazyload, this happens any time the actual number of images in the carousel is fewer than the number of items in the settings.

I have a responsive carousel in a mobile site where the items are database driven, so it's possible that at a certain screen width we may not have enough items to fill the screen, depending on the page in the site. My settings are:

```
loop:true,
lazyLoad:true,
slideBy: 'page',
dots:true,
items: 2,
responsive:{
    0:{ items:2 },
    568:{ items:3 },
    768:{ items:4 },
    900:{ items:5 },
    1000:{ items:6 }
}
```
As @galatent noted, this appears to be at least partially due to an issue with the Lazy function, where the number of "clones" is returning zero in this case, so even though it's running the load function the correct number of times, it's always passing index "0". 

My workaround may not be the best solution in all scenarios, but it seems to have worked for our situation, and I was more hesitant to replace an entire function. I wrapped the following block in a condition to check for the number of clones. so changed:

```
while (i++ < n) {
    this.load(clones / 2 + this._core.relative(position));
    clones && $.each(this._core.clones(this._core.relative(position++)), load);
}
```
to:
```
if (clones > 0) {
    while (i++ < n) {
        this.load(clones / 2 + this._core.relative(position));
        clones && $.each(this._core.clones(this._core.relative(position++)), load);
    }
} else {
    while (i < n) {
        this.load(i);
        i++;
    }
}

**Comment by galatent** [comment]
I've tested the modification @flyrootmedia supplied and it works great.
I also agree with your analysis about it happening when the number of images is less than the number specified for the carousel. For example I tried it with a setting of 4 and it didn't work with 2 or 3 images.
In my project when the setting is 3, the problem will only ever occur for products which specifically have 2 images, which is a rare occurrence (maybe 3 products out of 1000).

**Comment by soundsbeard** [comment]
for some reason the fix provided by @flyrootmedia didn't work for me.
I've got 15+ elements in the slider and after refreshing the page 6 of them (set in reponsive option) loaded but others didn't just like there is nothing to load.
btw I've tried both with <img> and <div> as the element of a slider 

but @galatent post was very usefull. it works fine with your fix.
thank you gyus.

**Comment by arnocl** [comment]
Sorry for reopening this issue, but I see the code of @galatent was used in the last version. The problem still exists. My code, found at [http://www.loreleywines.be/index2.php](url) changes the content based on result from ajax call, clicking "Duitsland" (Germany) only returns 2 items, when the carousel has 4 items in high resolution. The lazy load isn't working.

I want to change the options (reduce items when there's this issue) of the carousel dynamically, but I see the trigger (changeOption) was removed in later versions...

Thanks for your response
