### ISSUE TITLE
[Autoplay] Play restarts afert a next/prev or dots click

### ISSUE THREAD

**Issue by mfvitale** [OwlCarousel2/OwlCarousel2#1179]
If the carousel is stopped and I press the next/prev or dots button the carousel starts automatically.

Is this a features or a bug?

**Comment by tdecaluwe** [comment]
There is indeed some weird behavior in the interaction between the nav/dots and autoplay. I can reproduce by directly clicking stop in the autoplay demo included in the repo, and clicking one of the dots directly afterwards. However, sometimes it functions as expected, so there is something strange going on with the internal state of the plugin.

I included a fix in PR #1039 since this PR also exhibited this bug.

**Comment by mfvitale** [comment]
I also resolved here https://github.com/mfvitale/OwlCarousel2/blob/develop/src/js/owl.autoplay.js

**Comment by daviddeutsch** [comment]
See #1942
