### ISSUE TITLE
image stuck together

### ISSUE THREAD

**Issue by vandivicario** [OwlCarousel2/OwlCarousel2#1241]
hello im using owl-responsive

and every time the first load begin the image show like this

![untitled1](https://cloud.githubusercontent.com/assets/16689834/13180204/163460d2-d75a-11e5-96b5-a3ade9a086a7.png)

and if i minimize or inspect element the bug is gone

like this:
![untitled](https://cloud.githubusercontent.com/assets/16689834/13180237/30e811bc-d75a-11e5-8aac-a376d68dfb92.png)

heres my code:

```
<link href="css/owl.carousel.css" rel="stylesheet" media="all">
<div id="slider">
                        <div class="owl-carousel">
                          <div> <img src="http://placehold.it/100x100"  alt=""> </div>
                          <div> <img src="http://placehold.it/100x100"  alt=""> </div>
                          <div> <img src="http://placehold.it/100x100"  alt=""> </div>
                          <div> <img src="http://placehold.it/100x100"  alt=""> </div>
                          <div> <img src="http://placehold.it/100x100"  alt=""> </div>
                          <div> <img src="http://placehold.it/100x100"  alt=""> </div>
                          <div> <img src="http://placehold.it/100x100"  alt=""> </div>
                        </div>
                      </div>
<script src="js/owl.carousel.min.js"></script>
```

```
$('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:3,
                nav:false
            },
            1000:{
                items:5,
                nav:true,
                loop:false
            }
        }
    })
```

how can i fix it please? thanks

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
