### ISSUE TITLE
Question about OwlCarousel 2.0.0-beta.3

### ISSUE THREAD

**Issue by rapidpace** [OwlCarousel2/OwlCarousel2#1263]
In beta 3 owl.carousel.js baseClass is missing and styles are not visible from owl.carousel.css and hardcoding their style, i.e. to change the class owl-carousel on his own, then when you reload the page reset the scroll position to the very beginning.
Need to add:
1. in Owl.Add Defaults to `baseClass: 'owl-carousel'`
2. `this.$element.toggleClass(this.settings.rtlClass, this.settings.rtl);` 

change to 

`this.$element.addClass(this.settings.baseClass).toggleClass(this.settings.rtlClass, this.settings.rtl);`

Or baseClass has finally removed in beta 3?

If you use a base class .owl-item, then refreshing the page resets the scroll position on the page.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
