### ISSUE TITLE
"Event is undefined" error

### ISSUE THREAD

**Issue by jomofcw** [OwlCarousel2/OwlCarousel2#1270]
Hello !

Using OWL Carousel 2.0.0-beta.2.4.
I'm facing an "event is undefined" error using the callback and I can't understand why...
Here is my code (here "event" is "e") : 
`jQuery(function($) {
	var
		$caroussel_conteneur	=	$('.caroussel-conteneur'),
		$caroussel_navigation	=	$('.caroussel-navigation')
	;
	if	($caroussel_conteneur.length>=1)
	{
		$caroussel_conteneur
			.owlCarousel
			(
				{
					autoplay:true,
					items:1,
					loop:true,
					onInitialized:
						function(e)
						{
							$caroussel_navigation.trigger('positionner',[e.item.index]);/* Here I get the "e is undefined" */
						}
				}
			)
		;
	}
});`

Any idea why, and how to fix it, please ?
Thanks for your help.

Regards,

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
