### ISSUE TITLE
Endless slider not working

### ISSUE THREAD

**Issue by vinoth44** [OwlCarousel2/OwlCarousel2#1275]
Endless loop is not working while using prev/next trigger. I have tried **navRewind: false** but still it is not working. Below is my code please check whether I missed anything or it is an issue with plugin. 

`var slider1 = $(".slider1-top .overview");
			
		slider1.owlCarousel({ 
                slideBy : 'page', 
                margin : 15,
                loop : true,
                navRewind: false,
                responsive:{
                        0:{ items:1 },
                        500:{ items:2 },
                        800:{ items:3 },
                        1150:{ items:4 },
                        1200:{ items:3 },
                        1450:{ items:4 },
                        1700:{ items:5 }
                } 
            });

//var slider1=$(".slider1-top .overview").data('owlCarousel');
			
$('.slider1-top .buttons.next').click(function(e){ e.preventDefault(); slider1.trigger('next.owl.carousel'); });
$('.slider1-top .buttons.prev').click(function(e){ e.preventDefault(); slider1.trigger('prev.owl.carousel'); });`

**Comment by andyinabox** [comment]
+1 I think I'm having this issue as well, haven't found a solution yet. In my case, I've found that the endless loop only seems to work when there are more than 2 pages worth of items. So if I'm showing 5 items per page, I need to have at least 11 items for it to loop, otherwise the slider just goes back & forth.

**Comment by andyinabox** [comment]
Also worth mentioning: playing with the `slideBy` value also has an effect. If I set `slideBy` to be `1`, I don't encounter the issue.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
