### ISSUE TITLE
Swiping through a row based table

### ISSUE THREAD

**Issue by tmaffia** [OwlCarousel2/OwlCarousel2#1278]
Hi,

I am trying to utilize this within my html table. 

Example layout:

```
<table>
  <tbody>
    <tr class="row1">
      <td class="col1"></td>
      <td class="col2"></td>
      <td class="col3"></td>
      <td class="col4"></td>
    </tr>
    <tr class="row2">
      <td class="col1"></td>
      <td class="col2"></td>
      <td class="col3"></td>
      <td class="col4"></td>
    </tr>
  </tbody>
```
The data in the table is ordered by row rather than columns (seems to be the problem here). Is there some way to identify these separate elements as part of the same owl-item, despite them being in different parent elements?

Example: All table-data elements with class="col1" would be part of the same item, regardless of which row they were in. 

I'm guessing there would be significant performance implications if I made an owl carousel for each row and somehow linked them together.

**Comment by tmaffia** [comment]
Synchronizing separate carousels seems to work. It runs in my browser with over 100 carousels without any frame rate issues. This is very useful for paging through tables or other structured data. 

Can there be an option to sync the dragging of carousels with the same class name?

Example:

```
$('.carousel').owlCarousel({
  option1: "foo",
  option2: "bar",
  synced: true,
});
```

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

If you are just looking for general support, please use a public service like stack overflow.
