### ISSUE TITLE
Option Info don't working

### ISSUE THREAD

**Issue by romulobarbosa** [OwlCarousel2/OwlCarousel2#1298]
In this last version the option info stoped of work.

**Comment by tcelestino** [comment]
I have to some problem. :sob:

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
