### ISSUE TITLE
Fixed Position Item

### ISSUE THREAD

**Issue by cyberwani** [OwlCarousel2/OwlCarousel2#1299]
I am using OwlCarousel 2 as slider. And, I have a requirement of fixed position for a word in all slides.

There is a way by adding an the text outside slider. And, set fixed position by css in slider. But, the issue is that the word is prefixed/suffixed by other words (different in each slide) which are sliding with every slide. So, the static text will part of each text. which will remain at same position.

Something like this
https://drive.google.com/file/d/0B31KWKZmcBzZWHpyX0xMUzZuRVk/view?usp=sharing

**Comment by daviddeutsch** [comment]
Since the .item div can hold whatever markup you want, it should be fine to just add an absolutely positioned div in each of them.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
