### ISSUE TITLE
V 2.1.0 click drag in reverse error

### ISSUE THREAD

**Issue by hvsh** [OwlCarousel2/OwlCarousel2#1335]
Hey David, 

Thanks for picking up this great plugin. With 2.1.0 there seems to be an error when click dragging backwards the carousel jumps a few items. Forward works fine. V2.0.0 does not have this error.

**Comment by daviddeutsch** [comment]
Can't really recreate that in the demo pages (which is my usual test for casual issues). Perhaps you could put together an example?

**Comment by hvsh** [comment]
No problem David, Ill set it up later in the day.

**Comment by daviddeutsch** [comment]
Much obliged, thanks for taking the time!

**Comment by daviddeutsch** [comment]
@hvsh in the meantime, this occurred in another, related issue and I have since recreated it in the demo pages. The Basic demo suffices - dragging back to slide 10 after loading triggers the incorrect behavior reliably.

**Comment by daviddeutsch** [comment]
It seems to only be checking for the relative id, not the absolute one, probably a simple fix...

**Comment by hvsh** [comment]
Hey David, apologies for not getting back, I have been a little busy with some work. Okay great you were able to recreate the issue, If I can help let me know.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

Thx you hvsh
