### ISSUE TITLE
Duplicate item when the loop option is true

### ISSUE THREAD

**Issue by stormit** [OwlCarousel2/OwlCarousel2#1351]
Hi man,

First of all, thank you very much for your awesome slider!!!

I have found an issue. Please take your time to check it for me. I created a new Pen on codepen.io. It is here [http://codepen.io/stormit/pen/KzBEPj](http://codepen.io/stormit/pen/KzBEPj)

It only has one item. But if I set the **loop** option to **true**, it will display many items (depend on the **responsive** option).

Best regards,

**Comment by tonykiefer** [comment]
Its a little buggy...nothing is ever perfect...here we have a great example of two different needs both using the same solution.  I had the same problem.  If you want to loop you must logically have more than one item in the collection.  If you only have one item you don't need to loop AND as a matter of fact you don't need the carousel.

I perform a check and I say something like

If model.images != null && model.images.alternates =! null 
      {populate my carousel}
else {populate this div instead}...

![capture](https://cloud.githubusercontent.com/assets/16153113/14897223/264f2c9c-0d4f-11e6-9591-528758fbc026.PNG)

In the example I provided you see the If Else statement.  I first do a check to see if there are any images.  Provided we have images I load a larger container with a full size image...after that container is loaded I check to see if there are more than one image I will load the actual carousel.  If there are not more than one images to load...then I forgo loading the carousel and continue to the Else statement where I load a standard div with the primary image and that's it.

We don't use the carousel for one image...Well if you want to loop through the same image over and over again then cool, but its not practical.  Its ok to make these decisions in code...just because we have a need for a specific add-on there may always be an exception so you must provide it.  If the code decides you don't need the add-on you also must provide the alternate solution.

I know this was long winded but I just wanted to be thorough.  My solution is a custom solution because I use dual synced carousels and my zoom is implemented by using fancybox, but the technique is the same.

**Comment by fe-rod** [comment]
I had a similar problem. I need the carousels to loop only if they have more elements than what the viewport allows. If less elements are shown then I want to set the carousel to loop false, and so, no duplicate items in it.

I made a quick and dirty fix you can check here: #1200 

I know it modifies the plugin file, but it was the fastest way I found to allow this behavior when responsive is a must.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

We have received your feature request and will evaluate the implementation of this. 

I can't give you an estimated date when or if this will be integrated into the project. This might happen when the main refactoring will take place.
