### ISSUE TITLE
owl.theme.default.min.css is empty

### ISSUE THREAD

**Issue by ignaciolarranaga** [OwlCarousel2/OwlCarousel2#1396]
Check out the dist, the files are empty.

**Comment by franzip** [comment]
I am also experiencing this problem.
Running `grunt dist` does not solve the problem since owl.theme.default.min.css is still empty.

**Comment by thhomas** [comment]
Same for me, file empty

**Comment by lianee** [comment]
see #1357 to build with grunt

**Comment by CracyCrazz** [comment]
Hey guys,

this error will be fixed once we migrated from grunt to gulp in the next few days.

I'll be pushing a hotfix later. 

David renamed the theme files in order to follow the sass conventions, but that breaks the sass compiler as its seeing those theme files as partials. A fix for this is to create the owl.theme.*.scss files and include the according partials.

Stay tuned.
