### ISSUE TITLE
Not possible to stop rewinding after last slide?

### ISSUE THREAD

**Issue by nford** [OwlCarousel2/OwlCarousel2#143]
When a carousel comes to the end of the items, I would like it to simply continue without rewinding. I've set both loop: true and navRewind: false but as yet no luck stopping  the text from rewinding after the 4th and last slide in this demo http://codepen.io/nford/pen/eArFk

Is there another setting option I'm not aware of, is this a bug, or is this not supported?

**Comment by klin90** [comment]
@nford and @witrin Have you find solution to this? I am currently working as a junior dev for Dramafever. Right now, I am trying to see if I can get the slider to move forward from the last page to the first page, instead of backwards. See http://www.dramafever.com/movies/ for example, you will notice that it goes backwards, which is awkward.
