### ISSUE TITLE
This is the code. i have tried it so many times but it is not working!! Please help

### ISSUE THREAD

**Issue by mudittayal21** [OwlCarousel2/OwlCarousel2#1453]
HTML
[asd - Copy.txt](https://github.com/OwlCarousel2/OwlCarousel2/files/323018/asd.-.Copy.txt)

CSS
[owl.carousel.txt](https://github.com/OwlCarousel2/OwlCarousel2/files/323023/owl.carousel.txt)

JS
[owl.carousel.txt](https://github.com/OwlCarousel2/OwlCarousel2/files/323027/owl.carousel.txt)
[jquery-1.9.1.min.txt](https://github.com/OwlCarousel2/OwlCarousel2/files/323031/jquery-1.9.1.min.txt)

i have attached the cod in txt format, please convert to html and HELP!!!

**Comment by mudittayal21** [comment]
<div class="owl-carousel" id="owldemo">
    <div class="item"><img src=""></div>
    <div class="item"><img src=""></div>
    <div class="item"><img src=""></div>
    <div class="item"><img src=""></div>
    <div class="item"><img src=""></div>
  </div>

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
