### ISSUE TITLE
Abandonware

### ISSUE THREAD

**Issue by mpash** [OwlCarousel2/OwlCarousel2#1566]
I would appreciate some movement on this package.
- It's been weeks since the last update.
- There are hundreds of unmanaged issues.
- 48 Pull requests have had no responses.

**Comment by rdeelstra** [comment]
I think the new guy (David) has health problems, not sure, when I visit his website:
http://valanx.org/

**Comment by mpash** [comment]
I 100% respect that, but we must also get this package moving again. I'm not trying to step forward as the maintainer, but we as a community need to step up and decide the future of this package, otherwise the possible adoption rate of this package will slowly decline. I'll see if he has a twitter or an e-mail to reach out to him at and see if there is anything we can do to take this burden away from him while he deals with what he needs to deal with.

**Comment by mpash** [comment]
He doesn't have a twitter that I could find but I did e-mail the address listed on his website.

**Comment by daviddeutsch** [comment]
I inherited this repo with over 500 issues filed and for a while, Pascal and myself have put a lot of effort into at least staying the course. While that was going on, we did a major systems analysis to find the root causes to most of the problems and things people happen to run into so that we can stop new issues from popping up. That was a month ago and we were delayed in getting to work on those plans because of a major crunch at work, but we should be able to return soon. That's the reason why the issues have jumped above the usual level.

You can read the result of our analysis in #1538. Actually, I would really like everybody to read it because until now, it has exactly zero comments. I would much prefer people chip into actually moving things instead of opening issues like this one or sending me personal emails (which is super weird, to be honest).

Please be respectful of the fact that we all have day jobs and families while trying to steer back a ship that had been way past abandonment for over a year before we even entered the scene. @CracyCrazz and myself are very lucky to have an employer that allows us to spend even the little time that we get on this.

**Comment by mpash** [comment]
@daviddeutsch It was like pulling teeth to get a response from you. If you don't have the time to maintain a popular package then you're going to encounter e-mails from your users asking why your software doesn't work. It took a basic whois report on your website and one e-mail later you're responding to your users. I consider that a success, not being weird. You're welcome OwlCarousel users!

**Comment by bitemyapp** [comment]
@mpash this isn't League of Legends customer support. You are not @daviddeutsch's customer, you use something he maintains for free on a professional network for programmers.

Do you want a thread where you're being entitled and difficult on the same account employers check? Further, being difficult isn't going to incentivize anyone to fix anything you care about.

**Comment by mpash** [comment]
@bitemyapp You're right. I'll just use another library that is maintained better.
