### ISSUE TITLE
Vertical Carousel

### ISSUE THREAD

**Issue by fabianchoxD** [OwlCarousel2/OwlCarousel2#1576]
Hi, i'm trying to make my carousel Vertical... How can do that ? 

thanks

**Comment by cantejuandavid** [comment]
Por lo que puedo leer no creo que esté implementado aún el vertical,  vea este issue #5

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #5, taking over this repo, we cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime.

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
