### ISSUE TITLE
Content in owlcarousel vanishes sometimes after animation

### ISSUE THREAD

**Issue by maplesyrupghost** [OwlCarousel2/OwlCarousel2#1616]
Hey!  Having an issue with a theme that uses the owlcarousel.  2.4 beta is the version in the theme.  Instead of showing your our site, I'll just show you the theme in question as it has the issue in their demo:

http://www.inspirothemes.com/polo-v2/home-construction.html

At first, the content in the slider will work, and this is a good example because there are only two slides.  Just load that page, let the two slides animate on their own, and the next time the 1st slide appears it will be fine, but when the 2nd slide enters it vanishes after the animation.  In our custom made site, we have 5 or 6 slides and the behaviour is that the 1st slide works, and then all the other slides will vanish ONLY after the first time they are all shown and it goes to come around a second time.  I would normally say this is a theme related issue and I should mention it there but it is evident in ALL of the layouts for this theme in their demo.  I can't think of a working example because the docs for the owl carousel are tiny and they don't show you anything that looks like this.  

I tried downgrading to 2.2 and it might take a bit of work to get that to even load at all, and version 1 looks even more difficult to downgrade to.  

So please let me know what a good solution would be for the vanishing content in these sliders.  

Thanks in advance.

**Comment by ohepworthbell** [comment]
I think the issue is a rendering bug in Chrome in terms of using both the CSS `position` and `transform` attributes at the same time. I have found that, in Chrome, any child elements of a slide with a position anything other than static (such as relative, for example) disappear whilst the slide is transitioning. It repairs immediately when the transition has finished. I also know that `transform: translate` overrides the `position` attribute in CSS, and can only assume that the 2 are related.

Maybe try removing any `position` attributes from child elements (use `transform: translate` instead, if you need to move things relatively) and see if that works?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by michael-lynch** [comment]
I was having this exact issue (Chrome and Safari iOS) and the solution proposed by @ohepworthbell - replacing all instances of `position: relative` with `transform: translate(0)` - seems to work.
