### ISSUE TITLE
Option `info` is deprecated but still in the documentation 

### ISSUE THREAD

**Issue by pipinov** [OwlCarousel2/OwlCarousel2#167]
Hi!
I can't understand, how can I use option info? In a particular: I need to get current item. 

Thanks!

PS: Your plugin is best from the best, thanks, again and again.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
