### ISSUE TITLE
Responsive - Height of it's parent

### ISSUE THREAD

**Issue by xApep** [OwlCarousel2/OwlCarousel2#1698]
Hi.
Is it possible that the owl-carousel adjust height (responsivly) regarding of the parent height?

As seen in the attachment, the content height is bigger than the carousel and then owl-carousel has "red / white" space benith itself. 

Is it possible that the owl-carousel get's height from it's parent and adjust image regarding it's parent height?

![untitled-5](https://cloud.githubusercontent.com/assets/1315340/22018989/c0627fbe-dcb1-11e6-94c4-57f37652351f.jpg)

Thanks.

**Comment by ohepworthbell** [comment]
To make it responsive, you will have to make a div with a width and height of 100% and then either use Javascript to work out whether the image needs to be set by width and height (cropping off the image with an `overflow: hidden` accordingly) or, as a simpler solution, you can set the image as a background image, and then simply set the declaration `background-size: cover` and have it automatically done for you. It shouldn't need saying, but both options will crop the image slightly at various sizes.

There is no way that Owl Carousel can do this for you, and whilst I can't speak for the developers, I can't see any future time that such a feature would be supported (since it is quite specific and can be achieved using just CSS by individual sites when needed)

**Comment by CracyCrazz** [comment]
There are a few ways to achieve such a thing, but it's to specific for us to implement such a feature like @ohepworthbell already mentioned.
