### ISSUE TITLE
Autoplay restarts after mouse/touch drag

### ISSUE THREAD

**Issue by Es2admin2** [OwlCarousel2/OwlCarousel2#1736]
I have tryed using the solution mentioned [here](https://github.com/OwlCarousel2/OwlCarousel2/issues/998), but as soon as the carousel is released the autoplay feature is restarted. Has anybody found another work-around?

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

I would rather like to fix this issue instead of working around it.
