### ISSUE TITLE
working with wordpress

### ISSUE THREAD

**Issue by Soph87** [OwlCarousel2/OwlCarousel2#1840]
Hi there!
I'm developping my first wordpress theme (I obviously have no idea what I'm doing) and I'm trying to use owl in my home page to display articles from a category. I followed the instruction on the website but I can't get the plugin to work. I have no idea what I'm doing wrong...
So, I added this in my header.php : 
```
<link rel="stylesheet" type="text/css" href="<?php echo get_template_directory_uri(); ?>/css/owl.theme.default.min.css" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
```
Then I added this into my main : 
```
<div id="contenu1">
		<div class="owl-carousel">
			<div>
				<img src="<?php echo esc_url(get_template_directory_uri()); ?>/images/dossier1.jpg">
			</div>
			<div>
				<img src="<?php echo esc_url(get_template_directory_uri()); ?>/images/dossier2.jpg">
			</div>
		</div>
	</div>
```
And then I added this into the footer.php : 

```
<script type="text/javascript" src="<?php bloginfo( 'template_url' ); ?>/js/owl.carousel.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
 		$(".owl-carousel").owlCarousel();
		});
	</script>
```
Right now I'm just trying to make it work with images, then I will try and use the loop to display the articles. My images show up one on top of the other and a prev and next text appeared also but that's it. 
What am I doing wrong? Can someone explain ? Bear in mind that I am not a developper....
Thank you! :)

**Comment by thomasdesign** [comment]
Have you tried opening up your browser's console (it's usually easily accessible through right click on a page and "Inspect element")?

Since you're using WordPress and inserting the JS code directly into the footer, you will probably have this error with your code:
`Uncaught TypeError: $ is not a function`

That's because WordPress runs jQuery in "No-Conflict mode". The easiest way for you to fix this is to replace your $ in the code with jQuery so it becomes:

`jQuery(document).ready(function(){
 	jQuery(".owl-carousel").owlCarousel();
});`

**Comment by elmorsy282** [comment]
i have same problem
