### ISSUE TITLE
autoplaySpeed is too fast.

### ISSUE THREAD

**Issue by sopheakpsp** [OwlCarousel2/OwlCarousel2#1961]
i try to set autoplay to be more slower, i have input value to 2000 but the it still so fast. How can i fix it?

jQuery(document).ready(function() {
  jQuery("#my-slider").owlCarousel({
      navigation : true, 
      slideSpeed : 2000,
      pagination : true,
      paginationSpeed : 400,
      singleItem:true,
      // video:true,
      autoPlay : true,
      autoplaySpeed:2000,
     navigationText: [
      "<i class='fa fa-angle-left'></i>",
      "<i class='fa fa-angle-right'></i>"
      ]
    });
});

**Comment by capachow** [comment]
Make it 7000? I found 7 seconds fits right for the projects I use it for.

**Comment by sopheakpsp** [comment]
thank you capachow.

**Comment by capachow** [comment]
No worries, just to clarify further, `autoplaySpeed` changes the speed of 'transition' and `autoplayTimeout` changes the time between switching. It was the latter that I preferred between 5-7 seconds. I just wanted to be clear incase you were referring to the former.

**Comment by daviddeutsch** [comment]
See #1942

**Comment by JenODea** [comment]
I know i'm super late to the game but I had this same issue and instead of adding an autoplayspeed: 10000, (since it didn't work for me) I found that if you have autoPlay: true, set the default is 5000 milliseconds, but if you change it to  autoPlay: 10000 you can get it to stay for 10 seconds (10000 milliseconds) and it will work so instead of trying to add another item in there just change the 'true' to the timing you want and it will fix the issue.

I found this on Owl Carousel's site here: http://www.landmarkmlp.com/js-plugin/owl.carousel/

**Comment by zainshabir00** [comment]
use this..
`smartSpeed: 1000` or `smartSpeed: 700`
will solve your problem brother.

[International Foundation Of Islam](https://ifislam.com)

**Comment by Nimash68** [comment]
@zainshabir00 Perfect!

**Comment by kgrant-rp** [comment]
Currently experiencing the same issues.
Docs are terrible - they do not explain what the actual options do.
There are 15 options for 'speed' but nothing works.
I mean I have been working with sliders like this for years and literally none of the options work.

Not much else to say.

**Comment by KenobySky** [comment]
Same issue here. None of the options are working.

**Comment by sangharshalkurn** [comment]
use

smartSpeed:3000,

**Comment by ComandPromt** [comment]
use  to stop	

~~~js

	$(document).ready(function(){
				
				var owl = $('.owl-carousel');
				
				owl.trigger('stop.owl.autoplay');
			  				
	});

~~~

**Comment by ssplaman** [comment]
chutiya hai kya bc
