### ISSUE TITLE
rewind false is not working when slideBy is set to 'page'

### ISSUE THREAD

**Issue by gauravdaxini** [OwlCarousel2/OwlCarousel2#2099]
rewind false is not working when slideBy is set to 'page'. It appears that buttons are disabled but when you click on the button, it will rewind. Please check [this jsfiddle](https://jsfiddle.net/ohcarghq/) for the same.

We are currently using the version 1.3.2 which works perfectly with their respective older options. But, now we are forced to move to version 2.* as our CI build fails due to the removal of an older repository.

Please help to fix this.

**Comment by weplan9** [comment]
I am having the exact same issue. When the option slideby is set to "page"

So my fix was to actually calculate the number of items and input the numeric values.

`slideBy: 4`

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

This is a old request and as mentioned in #1307, taking over this repo, we cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime.

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
