### ISSUE TITLE
In Owl carousel Custom transition is not working between last and first slide while loop mode is true

### ISSUE THREAD

**Issue by Jishnuparakkat** [OwlCarousel2/OwlCarousel2#2117]
I'm using owl carousel version 2.0 
In that  transition between first slide and last slide is not working while using loop mode kindly help me to solve this issue.

**Comment by MrMacStripe** [comment]
I've got the same problem as well.

**Comment by Jishnuparakkat** [comment]
What is the solution for this issue @MrMacStripe

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! As this one is already an older issue, I assume that you've found a solution for your problem. If that is not the case feel free to reply me and I will reopen this issue.

**Comment by ReneTuin** [comment]
@pascalporedda, we also have the same problem, see: https://2018.redmatters.com/test-rm/
When you reach end and go to first element animation is not correct.

**Comment by robizzt** [comment]
Same problem. It happens only when I add custom animations on elements inside of slides, when slider doesn't go to NEXT sibling, but to the first. And if the direction is reversed, same thing happens when slider doesn't go to PREV sibling, but goes to the last one. You can even see, for example, when dragging with mouse on last slide, if you drag to the side of PREV sibling, animation is there, but if you drag to the side of first slide, elements just disapere. Like, you can drag left-right, left-right, in specific moment on the last or first slide, and see elements disapereing and showing.

I think it would help if CLONED slides had class 'real-active' when their REAL slide is active, and otherwise if CLONED is active for REAL one to have class 'clone-active'.
Cause if I can set REAL and CLONED slide be always the same, no matter which is active, that bug could be avoided.
