### ISSUE TITLE
Invisible YouTube Videos 

### ISSUE THREAD

**Issue by sunilw** [OwlCarousel2/OwlCarousel2#2161]
If I create a simple carousel and inject videos using YouTube's iframe API, the videos are invisible.
I can see spaces where the videos should be.

The html can be seen here: https://gist.github.com/sunilw/47d9223053e951f73189ba753fd2a6f6

The JS I'm using: https://gist.github.com/sunilw/1d87f2e34329725f579d75eb6fb60da0

**Comment by soanvig** [comment]
Because of no live example I guess it happens because the size of Youtube frame is unknown during carousel initiation. You should define the size in either HTML or CSS before initiation.

Typical images situation use HTML size definition (the JS script knows the size of owl-item child, because the size of image is defined in browser structure).

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! As this one is already an older issue, I assume that you've found a solution for your problem. If that is not the case feel free to reply me and I will reopen this issue.
