### ISSUE TITLE
multiple carousel on a single page

### ISSUE THREAD

**Issue by MuhammadBilalMughal** [OwlCarousel2/OwlCarousel2#2229]
$(document).ready(function() {

var carouselCount = 0;
$(".owl-carousel").each(function () {
    $(this).attr("id", "owl-carousel" + carouselCount);
    $('#owl-carousel' + carouselCount).owlCarousel({
        items: 4,
        itemsDesktop: [1199, 4],
        itemsDesktopSmall: [980, 2],
        itemsTablet: [768, 1],
        itemsTabletSmall: false,
        itemsMobile: [479, 1],
        rewindNav: false,
        navigation: true,
        navigationText: ["Prev", "Next"],
        
        // Responsive 
        responsive: true,
        responsiveRefreshRate: 200,
        responsiveBaseWidth: window,
        
        //Pagination
        pagination: false
    });
    carouselCount++;
});
});

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, because you didn't provided any information.
