### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by mistergonza** [OwlCarousel2/OwlCarousel2#2474]
Simple example not work:
https://codepen.io/anon/pen/vVwvbw

wtf?

all browsers, mac os

I wasted many time for this... absolutely unusable plugin

**Comment by ohepworthbell** [comment]
You need to add a class of `owl-carousel` to the wrapping element - this will make the carousel work. This is mentioned in the [installation docs](https://owlcarousel2.github.io/OwlCarousel2/docs/started-installation.html).

This plugin - as with most on GitHub - is provided free of charge and maintained by sheer goodwill. The plugin also works and you didn't read the documentation properly. Making demands and saying, 'WTF?' will put a lot of people off helping you, especially when the issue is from not reading the documentation fully.

**Comment by mistergonza** [comment]
I solve this problem using own wrapper. But its not obviously when need use custom class for carousel and wrapper class usage is used for initialization plugin in examples. But it's my bad when i read documentation by diagonal, sorry for this.
