### ISSUE TITLE
Carousel works fine but it ruined sidebar

### ISSUE THREAD

**Issue by ljex** [OwlCarousel2/OwlCarousel2#2539]
Hi there, I have an issue with my template. I added owl carousel there, but then my sidebar stopped displaying properly on screen width higher than 1280px.

Not working example(with carousel):  http://test.empresario.sk
Working example(without carousel):  http://test1.empresario.sk

I was trying to change some css properties already but nothing worked.
Does anybody a clue what could be wrong?
Thank you!

**Comment by sachq** [comment]
Please post your code for further review?

**Comment by ljex** [comment]
> 
> 
> Please post your code for further review?

Can you specify what code (parts) should i provide? All I have is available on view-source:http://test.empresario.sk/. So do you need html, css and all js scripts? Thx

**Comment by keefyhub** [comment]
the issue is due to the width of the `#main` being set to `100%` with `flex-grow` also set to `1` rather than an issue with Owl Carousel. Without the carousel the `#main` doesn't have enough content to force itself to be 100% width. With the carousel it's pushing the `#sidebar` to get extra width.

You could solve this by setting the width of `#main` to be `width: calc(100% - 24em)` (or what ever the width of the sidebar is) or changing how you have used flexbox.

**Comment by ljex** [comment]
Thank You very much @keefyhub! The width: calc(100% - 24em); did the trick.
