### ISSUE TITLE
autoWidth with images not calculating stage width properly

### ISSUE THREAD

**Issue by sawyerh** [OwlCarousel2/OwlCarousel2#280]
I'm trying to use the new `autoWidth` option along with a carousel of images with varying widths, however I'm running into an issue where the carousel stage isn't being set wide enough, causing some of the items at the end to wrap. I've created a demo of the issue here: http://jsbin.com/devahije/2/edit?js,output

**Comment by vasilinka** [comment]
Hello, thank you very much for the library. 
What I came around currently the same bug is reproduced. Both in buid from development source and from available downloads. The link with owl.carousel from https://rawgit.com/witrin/OwlCarousel2/%23143/src/js/owl.carousel.js is not available(404).

**Comment by revxx14** [comment]
I'm also seeing this issue with the latest build. If I set `items: 3` and there are 24 items, the last item gets bumped to a new line. 24 / 3 = 8, so you'd think this would work fine. Removing one, leaving 23, and the issue is fixed. Removing another, leaving 22, and it's still fine. Removing one more, leaving 21, and it breaks. It seems like if the total is divisible by the number of items per page, it's dropping the last item to a new line.
