### ISSUE TITLE
Responsive Settings

### ISSUE THREAD

**Issue by Tekanewa** [OwlCarousel2/OwlCarousel2#326]
Hi,

when defining responsive breakpoints, the script seems to always use the overall screen width in order to determine the number of items, instead of the width that is actually available to the slider.

Example:
I have a two column layout and the slider is using the left column. Naturally, the column is only 50% of the available body width (or less, depending upon theme settings). But the slider still assumes that it has the full body width available, which is of course wrong. That results in overly small items since the defined breakpoints don't get called.

Also, when compared to owl-slider v1.x, the responsive settings overwrite the number of items that were specified with the "items" parameter. Wouldn't it be more sensible to use the "items" parameter as a kind of "maximum" setting, even if the responsive breakpoint settings might allow for more?

Example:
The slider is set to 4 items, using "items: 4" in the function call. The responsive breakpoints are set as follows:

<code>
responsive: {
    0: {
        items:          1,
    },
    480: {
        items:          2,
    },
    640: {
        items:          3,
    },
    960: {
        items:          4,
    },
    1280: {
        items:          6,
    }
},
</code>

For all available screen sizes of 960px or more, the defined item number of "4" should be used, even though the resolution of 1280px would allow for 6. In its current state, the script would use 6 items, even though the maximum should remain at 4.

I hope all this makes sense!

This is a great script and I'm really looking forward to the official realease of v2.0.

Kalydon

**Comment by MrCroft** [comment]
:( I know this is a very old issue, but I've just opened a new one for the exact opposite effect.
#1562
If you read it, you will understand that the behavior you mentioned above shouldn't be the desired behavior.
If I want to set a number of items for a certain resolution, I don't care about the space available to the carousel (because that is known to us), I actually care about the screen size. For 1366 laptops I want 5 items. But now, `1366: { items: 5 }` won't accomplish that anymore, because on 1366 on windows, owlCarousel sees 1349 (because of the 17px browser scrollbar). And the scrollbar style/width differs from OS to OS.
Normal behavior should be that owlCarousel takes into account the viewport size (window.innerWidth). Because the rest is known to us (whatever widths, paddings, margins we have in the css - therefore the space available to the carousel). But now, since the carousel isn't looking at the resolution, what we can't do now is set N items for 1366 resolution... :(
