### ISSUE TITLE
Change `nestedItemSelector` to `itemSelector`

### ISSUE THREAD

**Issue by sasindumendis** [OwlCarousel2/OwlCarousel2#396]
When I try initialize a carousal with `nestedItemSelector` option set, it does not work.

I created a JsFiddle here http://jsfiddle.net/N38PS/17/ and tested and noticed the same behavior on latest Chrome, Firefox and IE 10

I m using latest development

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
