### ISSUE TITLE
Scrolling to left problem

### ISSUE THREAD

**Issue by curiouspers** [OwlCarousel2/OwlCarousel2#511]
Using OwlCarousel2, and with 7 images and following options:
```javascript
    margin: 0,
    loop: true,
    nav: true,
    slideBy: 5,
    items: 6
```
screen resolution is 1920, and wrapper is 100% width.

problem is when i press ".owl-prev" button, first time everything is ok, but second, third, and so on - pictures on the right disapears instantly, and then animation starts.

Disabling -webkit-backface-visibility: hidden; is not helping

How to fix that?

**Comment by joeyjoejoejr** [comment]
Can someone verify this is still an issue? Is it only on master?  I don't think that master reflects the most recent builds right now.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
