### ISSUE TITLE
Autoplay slide with animate doesn't working well

### ISSUE THREAD

**Issue by lidya1859** [OwlCarousel2/OwlCarousel2#715]
I'm using animate.css for my slide effect and it works, but when it reach to the end and go back to the first slide the animation just messed up.
![screencapture](https://cloud.githubusercontent.com/assets/9672394/6321701/7e9c91d2-bb3e-11e4-803f-1ad6d5296f29.png)
As you see in my screencapture, class "animated" appears in "owl-item cloned". So the first image has showed up.
I don't know if its just me doing something wrong or it is a bug. Maybe anyone here have some problem? Any suggest for me? Thank you..
[*sorry for my poor english*]

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
