### ISSUE TITLE
Possible to set autoplayTimeout per item?

### ISSUE THREAD

**Issue by BjornFridal** [OwlCarousel2/OwlCarousel2#718]
Hi,

I need to set the autoplayTimeout on each item in owlCarousel. Is that supported in ownCarousel or is that something I would have to do manually?

Cheers
Bjørn

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
