### ISSUE TITLE
How to re-init component when it shows backbone collection items.

### ISSUE THREAD

**Issue by AndrewEastwood** [OwlCarousel2/OwlCarousel2#769]
I have BB collection and related view that renders all items and triggers custom event 'render:complete'.
And I have event handler for that and there I have smth like this:
```
                that.views.viewedProducts.$el.addClass('owl-carousel');
                that.views.viewedProducts.on('render:complete', function () {
                    that.views.viewedProducts.$el.owlCarousel({
                        stopOnHover: true,
                        rewindNav: false,
                        items: 6,
                        pagination: false,
                        loop: false,
                        itemsTablet: [768, 3],
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:3
                            },
                            1000:{
                                items:5
                            }
                        }
                    });
                });
```

and on each route I fetch new collection data and the 'render:complete' event is being triggered After further invokes I got broken carousel and error message appears:
```
Uncaught TypeError: Cannot read property 'indexAbs' of undefined
```

Is it possible to solve this problem?

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
