### ISSUE TITLE
How to make the carousel vertical

### ISSUE THREAD

**Issue by shyam1992** [OwlCarousel2/OwlCarousel2#770]
Please do reply if there is already an option to set the direction of the carousel,if not consider this as an issue and try to give a solution:)

**Comment by leandroruel** [comment]
this is not a issue, ia a normal and common behavior.

**Comment by shyam1992** [comment]
Are you saying carousel can happen only in horizontal direction?

**Comment by leandroruel** [comment]
no, but, you don't see many vertical carousels through the web

**Comment by drakmail** [comment]
Maybe, you can try to use another great library - iScroll. But it is low-level library and you will need to implement carousel functionality manually.

**Comment by damreywil** [comment]
I wouldn't consider this an issue per se. In my opinion, this would be best suited as a plugin to OC2 due to vertical carousel functionality being a rarity.

@shyam1992 : If you are still looking for a solution since this functionality is not available (yet?), you might want to check out Cycle2 (http://jquery.malsup.com/cycle2/). They take the same plugin approach to making vertical possible (plugins are at the bottom of the downloads page). Hope that helps.

**Comment by shyam1992** [comment]
Thank you Williams 

-----Original Message-----

**Comment by leandroruel** [comment]
please close the issue

**Comment by ezsper** [comment]
I would like this feature in this, I love owl carousel and I would love to use this to list events and playlists responses vertically.

**Comment by AshboDev** [comment]
I too would +1 a vertical option. I'm currently developing a bespoke eCom site where the product detail has a normal carousel on mobile, and a vertical one on desktop. If there was an option for this, and perhaps a separate stylesheet (to stop unused CSS being duplicated), it would definitely help. I'm going to check out the link @damreywil posted, see if I can get anywhere with it.
