### ISSUE TITLE
Slider size is too large on iPad when inside container with percentage width

### ISSUE THREAD

**Issue by TcPhilBushnell** [OwlCarousel2/OwlCarousel2#781]
Hi,

I've come across that the slider is the wrong size on iPad when it's inside a container that has a percentage width on it. I first saw this when it was inside a lightbox but I have isolated it here: http://jsfiddle.net/rs7ngx98/

Setting a fixed size on the container, carousel element or outer staging element fixes the issue but requires javascript to update this responsively.

Regards,

**Phil Bushnell**

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
