### ISSUE TITLE
autoplayHoverPause: true not working

### ISSUE THREAD

**Issue by Gerrit74** [OwlCarousel2/OwlCarousel2#786]
Hi,
autoplayHoverPause: true  is not/not always working when the element is a youtube-video. 
I embedded a youtube video (iframe id="lb_player" src="//www.youtube.com/embed/Y...?wmode=transparent&amp;rel=0&amp;showinfo=0&amp;autohide=1) along with some img. While pausing the loop when hovering over img works fine, it doesn't (always) work when hovering over a running youtube video.
Seems to be a bug ...

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
