### ISSUE TITLE
lazyLoad don't work properly with responsive option and dynamic content

### ISSUE THREAD

**Issue by shorstki** [OwlCarousel2/OwlCarousel2#799]
When lazyLoad is on, and there is responsive number of items, images are loaded only for first item on carousel page.

I've isolated it here: http://jsfiddle.net/qx90s8cs/2/
Confirmed on latest Chrome and Firefox. Also IE 11.

**Edit:** probably changing while loop in _handlers of Lazy plugin to this:
````
while (i++ < n) {
	this.load(clones / 2 + this._core.relative(position));
	clones && $.each(this._core.clones(this._core.relative(position)), load);
	position++;
}
````
 fixes the issue

**Next issue** is dynamic content - lazy load don't fire after `add.owl.carousel` or even `refresh.owl.carousel`. I've tried to add refresh listener to _handlers object:
````
'initialized.owl.carousel change.owl.carousel refresh.owl.carousel'
````
But this didn' helped. I've solved it in dirty way triggering `initialized.owl.carousel` after refreshing... But I hope there is a better way ;)

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
