### ISSUE TITLE
Dragging Vertically on a Horizontal Carousel breaks the drag handler

### ISSUE THREAD

**Issue by Sinistralis** [OwlCarousel2/OwlCarousel2#808]
This is pretty easy to recreate even on the demo pages. Click and hold on an item, scroll up or down (Even a little), and then try to drag left to right. It won't work at all. This seems to occur on all modern browsers.

If you have URL Hash navigation enabled on the items on the carousel, the location you started the failed drag will become a click if you end the failed drag on the same element.

**Comment by daviddeutsch** [comment]
Hi @Sinistralis - thanks for contributing the issue & PR!

I just tested this myself on the demo page and didn't see any locking when I was scrolling. Perhaps this was fixed in the meantime? I also tested it on the URL Hash Nav demo and it seemed to be responding as expected.

In general, I think it's a good idea that we do not block scrolling itself, perhaps that was the original intent of the code.
