### ISSUE TITLE
items with autowidth in Firefox subpixel breaks last item in carousel

### ISSUE THREAD

**Issue by drrobotnik** [OwlCarousel2/OwlCarousel2#888]
In FF i believe there is a sub-pixel rendering issue i've been struggling with. I can't find where you set the height on resize, but it could possibly be fixed when you update the height with the following snippet.

`itemwidth = Math.floor(window.innerWidth/length * 100) / 100 )`

https://cloudup.com/cDVAPdlyvUf

**Comment by drrobotnik** [comment]
Actually, looking into it more, that won't fix it because FF rounds the number anyway. It does seem like if you use percentage widths for the items it works 100% of the time in my test, but i don't fully understand how you're setting the responsive offsets.

**Comment by greg5green** [comment]
@drrobotnik Could you provide a live test case for us as detailed in the [README](https://github.com/smashingboxes/OwlCarousel2#bug-reports)? Thanks!

**Comment by drrobotnik** [comment]
http://owl.caava.co/

Use FF on OSX or Windows
window.innerWidth at ~1204px, the last item pops to a new line.

**Comment by ryl** [comment]
I've also been seeing this issue in firefox.

**Comment by bjblayney** [comment]
Looks like a width issue forcing that last item down to the second line. 

I added a few pixels (+10) to line 325 of owl.carousel.js -
'width': Math.abs(this._coordinates[this._coordinates.length - 1]) + (this.settings.stagePadding * 2) + 10,

Seems to ~~hack~~ fix the issue for me. Haven't had time to delve to deeply, but this quickly alleviates the issue and I haven't found any new problems because of it.

**Comment by mkieblesz** [comment]
I have same problem and it appears with autoWidth option.

It appears because items width doesn't include floating point, because jQuery is rounding them by default https://github.com/jquery/jquery/issues/1724.

So instead of `widths[iterator] = !grid ? this._items[iterator].width() : width * merge;` we should do this `widths[iterator] = !grid ? Math.ceil(this._items[iterator][0].getBoundingClientRect().width) : width * merge;` or something like that.

Then another problem appears with animation (last item is not fully visible), because we calculate transition value relative to the current item, not the remaining width of the last item.

**Comment by mkieblesz** [comment]
To fix transitioning to the last item of the carousel you need to fix position function.

Replace this
```
        filter: [ 'position' ],
        run: function() {
            this.animate(this.coordinates(this._current));
        }
```
with this
```
        filter: [ 'position' ],
        run: function() {
            if (this._current === this.maximum()) {
                // if it's last element we calculate position relativiely to full carousel width
                // instead of current position
                this.animate(this.$stage.parent().width()-this.$stage.width());
            }
            else {
                this.animate(this.coordinates(this._current));
            }
        }
```
Works also with rewind and loop.
