### ISSUE TITLE
The effect of hash

### ISSUE THREAD

**Issue by Volosojui** [OwlCarousel2/OwlCarousel2#893]
Hi, there.

My problem is that changing hash which doesn't belong to the owl.carousel has an effects on slider. When the url hash changes slider goes to the first slide. I can't understand why slider does it, because the default URLhashListener option is false.

Page is including three blocks:
 1. button (link to an anchor)
 2. slider (owl.carousel2)
 3. registration form (anchor)

To run owl.carousel I'm using the following js code:
```
$('[js-owl-carousel2]').owlCarousel({
  loop: true,
  center: true,
  autoWidth: true,
  dots: false,
  autoplay: true,
  autoplayTimeout: 2500,
  autoplaySpeed: 1000
})
```

Maybe am I doing something wrong?

**Comment by Volosojui** [comment]
You can see example here: http://www.owlcarousel.owlgraphic.com/demos/autoplay.html
When second slide is active, add any hash in the address bar.

**Comment by Alexufo** [comment]
https://github.com/smashingboxes/OwlCarousel2/issues/891

remove loop: true,

**Comment by Volosojui** [comment]
@Alexufo It didn't help.

You can take a look at the example 'Center without loop'. Shift to the second slide and add any hash. Slider will go to the first slide.

**Comment by romavab** [comment]
try to update to beta 3)
http://smashingboxes.github.io/OwlCarousel2/

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

This is a very old request and as mentioned in #1307, taking over this repo, I cannot go through the entire backlog and selfishly assume you have either found a solution or moved on in the meantime. 

If you still have an issue that you think is due to a bug, please do open a new ticket. When you do, please add a live code example where I can check out your problem. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

(And make sure you're using the latest Owl Version!)

If you are just looking for general support, please use a public service like stack overflow.
